
--Create Employees Table
CREATE TABLE Employees(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	InternalIdentifier NVARCHAR(12) NOT NULL UNIQUE,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	City NVARCHAR(25) NOT NULL,
	Country NVARCHAR(45) NOT NULL,
	BirthYear INT NOT NULL CHECK (BirthYear >= 1960 AND BirthYear <= 2004),
	Notes NVARCHAR(500) NULL,	
);

--CREATE PROJECTS TABLE
CREATE TABLE Projects(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ProjectName NVARCHAR(40) NOT NULL,
	ProjectDescription NVARCHAR(500) NULL,
	CustomerName NVARCHAR(50) NOT NULL,
	Revenue MONEY NOT NULL
);

--CREATE LINK TABLE
CREATE TABLE ProjectEmployees (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ProjectId INT NOT NULL FOREIGN KEY REFERENCES Projects(ID),
	EmployeeId INT NOT NULL FOREIGN KEY REFERENCES Employees(ID)
);


--MODIFY COLUMN TYPE
ALTER TABLE Employees 
ALTER COLUMN Country NVARCHAR(30);


--ADD CONSTRAINT ON COLUMN
ALTER TABLE Employees
ADD CONSTRAINT Set_Df
DEFAULT 'Not Existing Notes' for Notes


--DELETE COLUMN
ALTER TABLE Employees
DROP COLUMN Notes


--REMOVE CONSTRAINT ON COLUMN
ALTER TABLE Employees
DROP CONSTRAINT Set_Df


--ADD NEW COLUMN
ALTER TABLE Employees
ADD Notes NVARCHAR(500);


--DELETE TABLE
DROP TABLE Employees;

