CREATE TABLE Employees(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	InternalIdentifier NVARCHAR(12) NOT NULL UNIQUE,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	City NVARCHAR(25) NOT NULL,
	Country NVARCHAR(45) NOT NULL,
	BirthYear INT NOT NULL CHECK (BirthYear >= 1960 AND BirthYear <= 2004),
	Notes NVARCHAR(500) NULL,	
);

ALTER TABLE Employees 
ALTER COLUMN Country NVARCHAR(30);

ALTER TABLE Employees 
DROP COLUMN Country;

ALTER TABLE Employees
ADD Country NVARCHAR(45);

DROP TABLE Employees;
